version: '2.1'

# volumes:
#   authority0:

networks:
  poa:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.1/24
        gateway: 172.16.0.1

services:
  authority0:
    image: parity/parity:${PARITY_VERSION}
    command:
      --config /parity/config/authority.toml
      --engine-signer 0x00bd138abd70e2f00903268f3db08f2d25677c9e
      --unsafe-expose
    volumes:
      # - authority0:/root/.local/share/io.parity.ethereum/
      - ./config/parity/chain.json:/parity/config/chain.json:ro
      - ./config/parity/authority.toml:/parity/config/authority.toml:ro
      - ./config/parity/authorities/authority0.pwd:/parity/config/authority.pwd:ro
      - ./config/parity/authorities/authority0.json:/root/.local/share/io.parity.ethereum/keys/${NETWORK_NAME}/authority.json:ro
      - ./config/parity/authorities/authority0.network.key:/root/.local/share/io.parity.ethereum/network/key:ro
      - ./config/parity/keys:/root/.local/share/io.parity.ethereum/keys/${NETWORK_NAME}
    ports:
      - 8180:8180
      - 8545:8545
      - 8546:8546
      - 30303:30303
    networks:
      poa:
        ipv4_address: 172.16.0.10

  member0:
    image: parity/parity:${PARITY_VERSION}
    command: 
      --config /parity/config/member.toml
      --unsafe-expose
    volumes:
      - ./config/parity/chain.json:/parity/config/chain.json:ro
      - ./config/parity/member.toml:/parity/config/member.toml:ro
    ports:
      - 8181:8180
      - 8547:8547
    networks:
      poa:
        ipv4_address: 172.16.0.20

  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./config/monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
    networks:
      poa:
        ipv4_address: 172.16.0.100

  dashboard:
    image: buythewhale/ethstats
    volumes:
      - ./config/dashboard/ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - 8001:3000
    networks:
      poa:
        ipv4_address: 172.16.0.101

  explorer:
    # image: carechain/eth-explorer
    image: settlemint/ethexplorer
    ports:
      - 8000:8000
    environment:
      - GETH_HOSTNAME=${DOCKER_MACHINE_ADDR}
    networks:
      poa:
        ipv4_address: 172.16.0.102