[parity]
chain = "/parity/config/chain.json"

[rpc]
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
interface = "all"
origins = ["all"]
cors = "*"
hosts = ["all"]

[network]
bootnodes = [
    "enode://147573f46fe9f5cc38fbe070089a31390baec5dd2827c8f2ef168833e4d0254fbee3969a02c5b9910ea5d5b23d86a6ed5eabcda17cc12007b7d9178b6c697aa5@172.16.0.10:30303"
]

[ui]
interface = "all"
origins = ["all"]
cors = "*"
hosts = ["all"]

[websockets]
port = 8547
interface = "all"
origins = ["all"]
cors = "*"
hosts = ["all"]

[ipc]
disable = true